### PR TITLE
add ARM cpu targets

### PR DESCRIPTION
**Pull request by dobe**

### CODE REVIEW

**Comment by lppedd** [comment]
What about adding all native targets?  
Since @petertrr already deploys Apple targets, it should be possible to activate all of them (Tier 1/2/3).

Just need to be careful with automation, to avoid testing the same stuff 20 times.

**Comment by dobe** [comment]
@lppedd i agree with you, however as you say, i am also not aware about the overhead that is introduced here when adding additional targets. So I was adding just the ones that i currently need since i actually tested these. @petertrr please see this merely as a request to add at least those targets. Thanks upfront.

**Review by petertrr — APPROVED** [review]
LGTM! It's fine for me to add only these for now, and add additional targets later with a more careful look at tests and infrastructure

**Comment by petertrr** [comment]
@dobe could you also update the list of targets in the readme (or enable editing of the PR by maintainers)?

**Pull request merged**
